const {test}=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript')
const file=path.resolve(__dirname,'../src/lib/pose-coherence.ts'),m=new Module(file,module)
m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,file)
const {assessPoseCoherence:assess}=m.exports
// Synthetic derived measurements, not private research/video fixtures.
const ordinary={bodyHeight:.3,bboxAspect:.4,bboxArea:.04,torsoLength:.1,torsoAngle:0,sideVectorCosine:1}
const status=patch=>assess({...ordinary,...patch}).status
for(const [name,patch] of Object.entries({missing:{torsoAngle:undefined},nonfinite:{torsoAngle:NaN},infinity:{torsoLength:Infinity},zeroDenominator:{torsoLength:0},invalidExtent:{bodyHeight:-1},invalidAspect:{bboxAspect:0},invalidArea:{bboxArea:0},invalidAngle:{torsoAngle:181},invalidCosine:{sideVectorCosine:1.01}}))test('mathematical abstention: '+name,()=>{const r=assess({...ordinary,...patch});assert.equal(r.status,'INSUFFICIENT_EVIDENCE');assert.deepEqual(r.reasons.map(r=>r.code),['INSUFFICIENT_GEOMETRY']);assert.equal(r.reasons[0].tier,0)})
test('missing or unavailable input abstains',()=>{for(const x of [null,undefined,[],{}, {unavailable:'invalid dimensions'}])assert.equal(assess(x).status,'INSUFFICIENT_EVIDENCE')})
test('ordinary diagnostic is neutral, never certification',()=>{const r=assess(ordinary);assert.equal(r.status,'NO_OBVIOUS_ANOMALY');assert.equal(r.authority,'NONE');assert.deepEqual(r.reasons,[])})
for(const [name,patch]of Object.entries({asymmetry:{largestLeftRightAsymmetry:8},shortLimb:{limbTorsoRatios:[.01,1,1,1,1,1,1,1]},visibility:{minVisibility:0,maxConnectedVisibilityGap:1},overlap:{maxRetainedIou:1},smallAngle:{kneeAngles:[1,1],elbowAngles:[1,1]},distalReach:{distalTorsoMax:9},bbox:{bboxAspect:5}}))test(name+' alone is diagnostic-only',()=>assert.equal(status(patch),'NO_OBVIOUS_ANOMALY'))
test('weak extremes combined cannot promote or manufacture structural evidence',()=>{const weak={bboxAspect:5,largestLeftRightAsymmetry:9,distalTorsoMax:10,limbTorsoRatios:[0,0,0,0,0,0,0,0],kneeAngles:[0,0],minVisibility:0,maxRetainedIou:1};assert.equal(status(weak),'NO_OBVIOUS_ANOMALY');assert.equal(status({...weak,torsoAngle:150}),'SUSPICIOUS')})
test('null optional diagnostics do not invalidate available required geometry',()=>assert.equal(status({largestLeftRightAsymmetry:null,minVisibility:null,elbowAngles:[null,null]}),'NO_OBVIOUS_ANOMALY'))
test('each structural family alone is suspicious',()=>{assert.equal(status({torsoAngle:-150}),'SUSPICIOUS');assert.equal(status({sideVectorCosine:-.8}),'SUSPICIOUS')})
test('two distinct structural families produce strong suspicion with deterministic reasons',()=>{const r=assess({...ordinary,torsoAngle:150,sideVectorCosine:-.8});assert.equal(r.status,'STRONGLY_SUSPICIOUS');assert.deepEqual(r.reasons.map(x=>x.code),['INVERTED_IMAGE_TORSO','SHOULDER_HIP_VECTOR_OPPOSITION']);assert.deepEqual(r.reasons.map(x=>x.measurements),[{torsoAngle:150},{sideVectorCosine:-.8}])})
test('mathematical insufficiency takes precedence over structural reasons',()=>assert.equal(status({torsoLength:0,torsoAngle:150,sideVectorCosine:-1}),'INSUFFICIENT_EVIDENCE'))
test('broad geometric boundaries have explicit open edges',()=>{for(const a of [-90,90])assert.equal(status({torsoAngle:a,sideVectorCosine:0}),'NO_OBVIOUS_ANOMALY');for(const a of [-91,91])assert.equal(status({torsoAngle:a}),'SUSPICIOUS');assert.equal(status({sideVectorCosine:-.01}),'SUSPICIOUS');assert.equal(status({sideVectorCosine:1+Number.EPSILON}),'NO_OBVIOUS_ANOMALY')})
test('metadata including pose index, source, label, video and time never affects assessment',()=>{for(const source of ['FULL_FRAME','LEFT_CROP','RIGHT_CROP'])for(const poseIndex of [1,3,99])assert.deepEqual(assess({...ordinary,source,poseIndex,label:'MALFORMED',video:'ignored',timestamp:123}),assess(ordinary))})
test('deterministic and immutable, including nested diagnostics',()=>{const input={...ordinary,limbTorsoRatios:Object.freeze([.1,2])};Object.freeze(input);const a=assess(input),b=assess(input);assert.deepEqual(a,b);a.diagnostics.limbTorsoRatios[0]=5;assert.equal(input.limbTorsoRatios[0],.1);assert.deepEqual(assess(input),b)})
test('model import boundary excludes every product pipeline',()=>{function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)])}const users=walk(path.resolve(__dirname,'../src')).filter(p=>p!==file&&/\b(?:assessPoseCoherence|pose-coherence)\b/.test(fs.readFileSync(p,'utf8')));assert.deepEqual(users.map(p=>path.relative(path.resolve(__dirname,'..'),p).replace(/\\/g,'/')),['src/app/pose-test/RawPoseResearch.tsx']);const model=fs.readFileSync(file,'utf8');assert.doesNotMatch(model,/^import |fetch\(|localStorage|sessionStorage/m)})
test('evaluation groups correlated sources and preserves source-level results',()=>{const {evaluate}=require('./evaluate-pose-coherence.cjs');const row=(id,observation,patch)=>({id,set:'synthetic',observation,label:'COHERENT',measurements:{...ordinary,...patch}});const result=evaluate([row('a','same',{}),row('b','same',{torsoAngle:120,sideVectorCosine:-.5}),row('c','other',{})]);assert.equal(result.results.length,3);assert.equal(result.coherentObservations.STRONGLY_SUSPICIOUS,1);assert.equal(result.coherentObservations.NO_OBVIOUS_ANOMALY,1);assert.equal(result.distinct.length,2)})
