const {test,after}=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),Module=require('node:module'),ts=require('typescript')
const {execFileSync}=require('node:child_process')
function load(file,mocks={}){const name=path.resolve(__dirname,'..',file),m=new Module(name,module);m.filename=name;m.paths=module.paths;m.require=id=>id in mocks?mocks[id]:require(id);m._compile(ts.transpileModule(fs.readFileSync(name,'utf8'),{fileName:name,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText,name);return m.exports}
const h=load('src/lib/research-video-source.ts')
const root=fs.mkdtempSync(path.join(os.tmpdir(),'research-video-test-'))
const oldMode=process.env.NODE_ENV,oldRoot=process.env.PICKLEPRO_RESEARCH_VIDEO_DIR
for(const filename of ['one.mp4','two.MOV','three.webm','four.m4v','secret.env','notes.json'])fs.writeFileSync(path.join(root,filename),'0123456789')
fs.mkdirSync(path.join(root,'nested.mp4'))
after(()=>{if(oldMode===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=oldMode;if(oldRoot===undefined)delete process.env.PICKLEPRO_RESEARCH_VIDEO_DIR;else process.env.PICKLEPRO_RESEARCH_VIDEO_DIR=oldRoot;fs.rmSync(root,{recursive:true,force:true})})
function configure(){process.env.NODE_ENV='development';process.env.PICKLEPRO_RESEARCH_VIDEO_DIR=root}
const request=(range,method='GET')=>new Request('http://127.0.0.1:3005/pose-test/research-videos',{method,headers:range===undefined?{}:{Range:range}})
async function videos(){configure();return(await(await h.researchVideoIndex(request())).json()).videos}

test('loader disabled outside development even with configured root',async()=>{for(const mode of ['production','test','']){configure();process.env.NODE_ENV=mode;assert.equal((await h.researchVideoIndex(request())).status,404);assert.equal((await h.researchVideo(request(),'a'.repeat(64))).status,404)}})
test('root is required and must be absolute',async()=>{configure();for(const value of ['', 'relative-root']){process.env.PICKLEPRO_RESEARCH_VIDEO_DIR=value;assert.equal((await h.researchVideoIndex(request())).status,404)}})
test('only immediate regular files with supported video extensions are listed without paths',async()=>{const list=await videos();assert.deepEqual(list.map(v=>v.filename).sort(),['four.m4v','one.mp4','three.webm','two.MOV']);assert.ok(list.every(v=>Object.keys(v).sort().join(',')==='filename,id,url'));assert.ok(!JSON.stringify(list).includes(root))})
test('IDs are stable and change when a file version changes',async()=>{const a=await videos(),b=await videos();assert.deepEqual(a,b);const file=path.join(root,'one.mp4');fs.writeFileSync(file,'01234567890');const c=await videos();assert.notEqual(a.find(v=>v.filename==='one.mp4').id,c.find(v=>v.filename==='one.mp4').id);fs.writeFileSync(file,'0123456789')})
test('index URLs stay on the browser origin even when Next normalizes its internal host',async()=>{for(const v of await videos()){assert.equal(v.url,`/pose-test/research-videos/${v.id}`);assert.equal(new URL(v.url,'http://127.0.0.1:3005').origin,'http://127.0.0.1:3005')}})
test('traversal and arbitrary absolute paths are rejected',async()=>{configure();for(const id of ['../one.mp4','%2e%2e%2fone.mp4','one.mp4','/etc/passwd','C:\\private\\secret.mp4','a'.repeat(64)])assert.equal((await h.researchVideo(request(),id)).status,404)})
test('non-loopback and cross-origin requests are rejected',async()=>{configure();for(const req of [new Request('http://example.com/pose-test/research-videos'),new Request('http://127.0.0.1:3005/pose-test/research-videos',{headers:{Origin:'https://example.com'}}),new Request('http://127.0.0.1:3005/pose-test/research-videos',{headers:{'Sec-Fetch-Site':'cross-site'}})])assert.equal((await h.researchVideoIndex(req)).status,404)})
test('actual Host is validated despite Next normalized URLs, and legitimate browser origin is accepted',async()=>{configure();const url='http://localhost:3005/pose-test/research-videos';assert.equal((await h.researchVideoIndex(new Request(url,{headers:{host:'evil.example'}}))).status,404);assert.equal((await h.researchVideoIndex(new Request(url,{headers:{host:'127.0.0.1:3005',origin:'http://127.0.0.1:3005'}}))).status,200)})
test('directory links cannot expose files outside root',async()=>{const outside=fs.mkdtempSync(path.join(os.tmpdir(),'research-outside-'));const link=path.join(root,'escape.mp4');try{fs.writeFileSync(path.join(outside,'private.mp4'),'PRIVATE');fs.symlinkSync(outside,link,'junction');assert.ok(!(await videos()).some(v=>v.filename==='escape.mp4'));assert.equal((await h.researchVideo(request(),'escape.mp4/private.mp4')).status,404)}finally{if(fs.existsSync(link))fs.unlinkSync(link);fs.rmSync(outside,{recursive:true,force:true})}})
test('all supported MIME types and full response bytes/length are correct',async()=>{for(const v of await videos()){const response=await h.researchVideo(request(),v.id);assert.equal(response.status,200);assert.equal(response.headers.get('Content-Type'),v.filename.endsWith('MOV')?'video/quicktime':v.filename.endsWith('webm')?'video/webm':'video/mp4');assert.equal(response.headers.get('Content-Length'),'10');assert.equal(response.headers.get('Accept-Ranges'),'bytes');assert.equal(response.headers.get('Content-Range'),null);assert.equal(await response.text(),'0123456789')}})
test('valid bounded, open-ended, suffix and clamped ranges stream exact bytes',async()=>{const v=(await videos())[0];for(const [range,body,content] of [['bytes=2-5','2345','bytes 2-5/10'],['bytes=7-','789','bytes 7-9/10'],['bytes=-3','789','bytes 7-9/10'],['bytes=8-99','89','bytes 8-9/10'],['bytes=-99','0123456789','bytes 0-9/10']]){const response=await h.researchVideo(request(range),v.id);assert.equal(response.status,206);assert.equal(response.headers.get('Content-Range'),content);assert.equal(response.headers.get('Content-Length'),String(body.length));assert.equal(await response.text(),body)}})
test('invalid/multiple/unsatisfiable ranges return 416 and total length',async()=>{const v=(await videos())[0];for(const range of ['bytes=10-','bytes=7-2','bytes=-0','bytes=-','bytes=0-1,4-5','items=1-2','bytes=999999999999999999999-']){const response=await h.researchVideo(request(range),v.id);assert.equal(response.status,416,range);assert.equal(response.headers.get('Content-Range'),'bytes */10');assert.equal(await response.text(),'')}})
test('HEAD supplies seek headers without a body',async()=>{const response=await h.researchVideo(request('bytes=1-3','HEAD'),(await videos())[0].id);assert.equal(response.status,206);assert.equal(response.headers.get('Content-Length'),'3');assert.equal(await response.text(),'')})
test('replaced files cannot be accessed through stale IDs',async()=>{const v=(await videos()).find(v=>v.filename==='one.mp4');fs.appendFileSync(path.join(root,'one.mp4'),'new');assert.equal((await h.researchVideo(request(),v.id)).status,404)})
test('capture harness, Shadow model, product page and production routes remain frozen',()=>{for(const file of ['src/lib/research-capture.ts','src/lib/pose-coherence.ts','src/app/pose-test/page.tsx']){assert.equal(fs.readFileSync(path.resolve(__dirname,'..',file),'utf8').replace(/\r\n/g,'\n'),execFileSync('git',['show',`4479a0681a879d8afd2ead31fb96795a266b9e4e:${file}`],{encoding:'utf8'}).replace(/\r\n/g,'\n'))}assert.equal(execFileSync('git',['diff','4479a068','--','src/app/video-review','src/app/api'],{encoding:'utf8'}),'')})

test('selector ignores old metadata/error callbacks after switching and returns new identity',async()=>{
 configure();const slots=[];let index=0;const calls=[];const react={useEffect:()=>{},useState:init=>{const i=index++;if(!(i in slots))slots[i]=init;return[slots[i],v=>slots[i]=v]},useRef:init=>{const i=index++;if(!(i in slots))slots[i]={current:init};return slots[i]}}
 const jsx=(type,props)=>({type,props});const Component=load('src/app/pose-test/ResearchVideoSource.tsx',{'react':react,'react/jsx-runtime':{jsx,jsxs:jsx}}).default
 const render=()=>{index=0;return Component({onChange:(...args)=>calls.push(args)})}
 const find=(tree,type)=>{if(!tree||typeof tree!=='object')return;if(tree.type===type)return tree;for(const child of [tree.props?.children].flat(Infinity)){const found=find(child,type);if(found)return found}}
 const oldWindow=global.window;global.window={location:{href:'http://127.0.0.1:3005/pose-test'}}
 render();const a={id:'a',filename:'a.mp4',url:'http://127.0.0.1:3005/a'},b={id:'b',filename:'b.mp4',url:'http://127.0.0.1:3005/b'};slots[0]=[{...a,url:'/a'},{...b,url:'/b'}]
 find(render(),'select').props.onChange({target:{value:'a'}});const old=find(render(),'video')
 find(render(),'select').props.onChange({target:{value:'b'}});const fresh=find(render(),'video')
 const metadata={currentTarget:{duration:10,videoWidth:100,videoHeight:100}}
 old.props.onLoadedMetadata(metadata);old.props.onError();assert.deepEqual(calls,[[a,false],[b,false]])
 fresh.props.onLoadedMetadata(metadata);assert.deepEqual(calls.at(-1),[b,true]);assert.ok(JSON.stringify(render()).includes('b.mp4'))
 find(render(),'select').props.onChange({target:{value:''}});assert.deepEqual(calls.at(-1),[null,false]);assert.equal(find(render(),'video'),undefined)
 process.env.NODE_ENV='production';assert.equal(render(),null);global.window=oldWindow
})
