const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const {execFileSync}=require('node:child_process');
function load(file,mocks={}){const name=path.resolve(file),m=new Module(name,module);m.filename=name;m.paths=module.paths;m.require=id=>id in mocks?mocks[id]:require(id);m._compile(ts.transpileModule(fs.readFileSync(name,'utf8'),{fileName:name,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText,name);return m.exports}
const h=load('src/lib/research-review.ts'),p=load('src/lib/pose-research.ts'),shadow=load('src/lib/pose-coherence.ts');
const points=Array.from({length:33},(_,i)=>({x:.3+(i%2)*.2,y:.1+i*.02,visibility:.9}));
const row=()=>({id:'f1:left:7',stage:'raw',label:'UNLABELED',note:'',video:'fixture',fingerprint:'source-A',requestedTime:2.6,actualTime:2.596667,frameId:'frame-A',frameFingerprint:'pixels-A',sourceImageFingerprint:'crop-A',source:'LEFT_CROP',passPose:2,poseIndex:7,measurements:p.measurePose(points,300,700),image:'data:image-A',rawImage:'data:crop-A',width:1000,height:700,rawWidth:300,offsetX:400,points:structuredClone(points)});
function walk(n,pred,out=[]){if(!n||typeof n!=='object')return out;if(pred(n))out.push(n);for(const child of [n.props?.children].flat(Infinity))walk(child,pred,out);return out}
function harness(workspace=false){const slots=[];let index=0,current=row(),calls=0;const actions=[];const react={useEffect:()=>{},useRef:v=>{const i=index++;return slots[i]??(slots[i]={current:v})},useState:v=>{const i=index++;if(!(i in slots))slots[i]=typeof v==='function'?v():v;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v]}};const jsx=(type,props)=>({type,props});const c=load('src/app/pose-test/RawPoseReview.tsx',{'react':react,'react-dom':{createPortal:n=>n},'react/jsx-runtime':{jsx,jsxs:jsx},'@/lib/pose-research':p,'@/lib/research-review':h,'./RawPoseReview.module.css':{default:{workspace:'workspace',image:'image',record:'record'}}});const props=()=>({row:current,records:[current,{...row(),id:'f2:left:7',frameId:'frame-B',image:'data:image-B'}],selectedId:current.id,onSelect:id=>actions.push(id),onAction:(id,a)=>{actions.push(a);current=h.reviewAction(current,a)},assess:m=>{calls++;return shadow.assessPoseCoherence(m)}});const render=()=>{index=0;return workspace?c.default(props()):c.ReviewPose(props())};return{render,get row(){return current},get calls(){return calls},actions,find:(tree,label)=>walk(tree,n=>n.props?.['aria-label']===label)[0],button:(tree,text)=>walk(tree,n=>n.type==='button'&&n.props.children===text)[0]}}
test('reveal rejects unlabeled records and never assigns a label',()=>{const r=row();assert.throws(()=>h.reviewAction(r,{type:'reveal',at:'1'}),/Commit/);assert.equal(r.label,'UNLABELED')});
test('commit is immutable and preserves measurement identity',()=>{const r=row(),n=h.reviewAction(r,{type:'commit',label:'COHERENT',note:'visual',at:'1'});assert.equal(r.label,'UNLABELED');assert.equal(n.measurements,r.measurements);assert.equal(n.review.originalLabel,'COHERENT')});
test('reveal locks original label and ordinary edits are rejected',()=>{let r=h.reviewAction(row(),{type:'commit',label:'MALFORMED',note:'visual',at:'1'});r=h.reviewAction(r,{type:'reveal',at:'2'});assert.throws(()=>h.reviewAction(r,{type:'commit',label:'COHERENT',note:'',at:'3'}),/locked/);assert.equal(h.reviewAction(r,{type:'reveal',at:'4'}).review.revealedAt,'2')});
test('adjudication requires reveal and reason, preserves original validation label',()=>{let r=h.reviewAction(row(),{type:'commit',label:'UNCERTAIN',note:'',at:'1'});assert.throws(()=>h.reviewAction(r,{type:'adjudicate',label:'COHERENT',reason:'ownership',at:'2'}));r=h.reviewAction(r,{type:'reveal',at:'2'});assert.throws(()=>h.reviewAction(r,{type:'adjudicate',label:'COHERENT',reason:' ',at:'3'}));const n=h.reviewAction(r,{type:'adjudicate',label:'COHERENT',reason:'ownership resolved',at:'3'});assert.equal(n.label,'UNCERTAIN');assert.deepEqual(n.review.adjudications,[{originalLabel:'UNCERTAIN',revisedLabel:'COHERENT',reason:'ownership resolved',at:'3'}])});
test('navigation order and boundary behavior are deterministic',()=>{assert.equal(h.adjacentReview(['a','b','c'],'b',1),'c');assert.equal(h.adjacentReview(['a','b','c'],'b',-1),'a');assert.equal(h.adjacentReview(['a','b'],'b',1),'b');assert.equal(h.adjacentReview([],null,1),null)});
test('unlabeled filter excludes final rows and retains raw order',()=>{const rows=[row(),{...row(),id:'final',stage:'final'},{...row(),id:'labeled',label:'COHERENT'}];assert.deepEqual(h.reviewIds(rows,true),['f1:left:7']);assert.deepEqual(h.reviewIds(rows,false),['f1:left:7','labeled'])});
test('crop-to-display mapping, fit and zoom never alter raw coordinates',()=>{const original=JSON.stringify(points),mapped=h.rawDisplayPoints(points,300,700,400);assert.equal(mapped[0].x,490);const view=h.fitPlayer(mapped,1000,700);assert.ok(view.width<1000);assert.ok(h.zoomView(view,.7,1000,700).width<view.width);assert.equal(JSON.stringify(points),original)});
test('one overlay binds selected frozen image and fingerprint to provenance',()=>{const x=harness(),tree=x.render(),svg=x.find(tree,'Blinded raw pose overlay');assert.equal(walk(tree,n=>n.type==='svg').length,1);assert.equal(walk(svg,n=>n.type==='image')[0].props.href,x.row.image);assert.equal(svg.props['data-record-id'],x.row.id);assert.equal(svg.props['data-frame-fingerprint'],x.row.frameFingerprint);assert.match(JSON.stringify(tree),/frame-local #/);assert.match(JSON.stringify(tree),/2.596667/)});
test('zoom and pan component controls leave measurements and points unchanged',()=>{const x=harness(),before=JSON.stringify(x.row);let tree=x.render();x.button(tree,'ZOOM IN').props.onClick();tree=x.render();const svg=x.find(tree,'Blinded raw pose overlay');svg.props.onPointerDown({clientX:0,clientY:0,pointerId:1,currentTarget:{setPointerCapture(){}}});svg.props.onPointerMove({clientX:30,clientY:10,currentTarget:{getBoundingClientRect:()=>({width:514,height:537})}});assert.notEqual(x.find(x.render(),'Blinded raw pose overlay').props.viewBox,svg.props.viewBox);assert.equal(JSON.stringify(x.row),before)});
test('Shadow is absent and uncomputed before explicit committed label and reveal',()=>{const x=harness();let tree=x.render();assert.equal(x.calls,0);assert.equal(x.button(tree,'Reveal Shadow result').props.disabled,true);x.find(tree,'Blinded visual label').props.onChange({target:{value:'COHERENT'}});tree=x.render();assert.equal(x.row.label,'UNLABELED');assert.equal(x.button(tree,'Reveal Shadow result').props.disabled,true);x.button(tree,'Commit visual label').props.onClick();tree=x.render();assert.equal(x.calls,0);assert.equal(x.button(tree,'Reveal Shadow result').props.disabled,false);assert.equal(x.find(tree,'Revealed Shadow result'),undefined);x.button(tree,'Reveal Shadow result').props.onClick();tree=x.render();assert.equal(x.calls,1);assert.ok(x.find(tree,'Revealed Shadow result'));assert.equal(x.find(tree,'Blinded visual label').props.disabled,true);assert.equal(x.row.label,'COHERENT')});
test('Shadow result cannot influence label and human labels do not affect calculation',()=>{const r=row(),before=shadow.assessPoseCoherence(r.measurements);for(const label of ['COHERENT','MALFORMED','UNCERTAIN']){const labeled=h.reviewAction(r,{type:'commit',label,note:'',at:'1'});assert.deepEqual(shadow.assessPoseCoherence(labeled.measurements),before);assert.equal(labeled.label,label)}});
test('export adds adjudication metadata without exporting pixels or coordinates',()=>{let r=h.reviewAction(row(),{type:'commit',label:'COHERENT',note:'',at:'1'});r=h.reviewAction(r,{type:'reveal',at:'2'});const data=JSON.parse(h.withReviewHistory(JSON.stringify({rows:[{id:r.id,label:r.label}]}),[r]));assert.equal(data.rows[0].review.originalLabel,'COHERENT');assert.doesNotMatch(JSON.stringify(data),/data:image|rawWidth|points/)});
test('workspace portal is development-only and displays one selected record',()=>{const old=process.env.NODE_ENV,doc=global.document;try{global.document={body:{}};process.env.NODE_ENV='production';assert.equal(harness(true).render(),null);process.env.NODE_ENV='development';const x=harness(true);let tree=x.render();walk(tree,n=>n.type==='button'&&Array.isArray(n.props.children))[0].props.onClick();tree=x.render();assert.equal(walk(tree,n=>n.props?.row).length,1);assert.equal(walk(tree,n=>n.props?.role==='dialog').length,1)}finally{global.document=doc;if(old===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=old}});
test('526px layout keeps full-width image above wrapping controls',()=>{const css=fs.readFileSync('src/app/pose-test/RawPoseReview.module.css','utf8');assert.match(css,/@media \(max-width: 550px\)/);assert.match(css,/\.image \{ display: block; width: 100%/);assert.match(css,/\.controls \{ display: flex; flex-wrap: wrap/);const x=harness(),tree=x.render(),children=tree.props.children;assert.ok(children.findIndex(n=>n?.type==='svg')<children.findIndex(n=>n?.props?.['aria-label']==='Image view controls'))});
test('frozen capture, model, loader and product paths equal approved checkpoint',()=>{const files=['src/lib/pose-coherence.ts','src/lib/research-capture.ts','src/app/pose-test/ResearchVideoSource.tsx','src/app/pose-test/page.tsx'];for(const file of files){assert.equal(fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n'),execFileSync('git',['show',`2b0b5981f9f3dce1f74659d3d1eab88289e207e4:${file}`],{encoding:'utf8'}).replace(/\r\n/g,'\n'))}const src=fs.readFileSync('src/app/pose-test/RawPoseReview.tsx','utf8');assert.doesNotMatch(src,/fetch\(|localStorage|sessionStorage|setPersistent|setReferenceLedger|buildCoaching|detectMultiPass/)});
