const {test}=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript')
function load(file,mocks={}){const name=path.resolve(__dirname,'..',file),m=new Module(name,module);m.filename=name;m.paths=module.paths;m.require=id=>id in mocks?mocks[id]:require(id);m._compile(ts.transpileModule(fs.readFileSync(name,'utf8'),{fileName:name,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText,name);return m.exports}
const h=load('src/lib/research-capture.ts'),poseHelpers=load('src/lib/pose-research.ts')

// Simulates seeked becoming observable BEFORE the new surface is presented.
// Drawing outside the callback would retain the previous frame in this browser model.
function environment(mode='normal'){
  const old=global.document, videos=[]
  class Video extends EventTarget{
    constructor(){super();videos.push(this);this.duration=20;this.videoWidth=1920;this.videoHeight=1080;this.readyState=0;this.time=0;this.surface=-1;this.count=0;this.handles=new Map();this.serial=0;this.stopped=true;this.style={};this.seekCount=0;this.playRates=[]}
    setAttribute(){}
    remove(){}
    get paused(){return this.stopped}
    get currentTime(){return this.time}
    set currentTime(t){this.seekCount++;this.time=t;this.seeking=true;this.dispatchEvent(new Event('seeking'));setImmediate(()=>{if(mode==='abortSeek'||mode==='seekTimeout')return;if(mode==='errorSeek'){this.dispatchEvent(new Event('error'));return}this.readyState=4;if(mode==='presentationFirst'||(mode==='warmReadinessRace'&&this.seekCount===1)){if(mode==='warmReadinessRace')this.readyState=1;this.present(Math.floor(t*30+1e-7)/30);this.readyState=4;this.seeking=false;setImmediate(()=>this.dispatchEvent(new Event('seeked')))}else{this.seeking=false;this.dispatchEvent(new Event('seeked'));setImmediate(()=>{if((mode==='missingAll'&&this.seekCount===2)||(mode==='missingFirst'&&videos.indexOf(this)===0&&this.seekCount===2))return;this.present(mode==='stale'?0:Math.floor(t*30+1e-7)/30)})}})}
    load(){if(!this.src)return;setImmediate(()=>{if(mode==='loadTimeout')return;if(mode==='initialBeforeData'){this.readyState=1;this.present(0);this.readyState=4;this.dispatchEvent(new Event('loadeddata'));return}this.readyState=4;this.dispatchEvent(new Event('loadeddata'));this.present(0)})}
    present(pts){this.surface=pts;this.count++;const callbacks=[...this.handles.values()];this.handles.clear();this.inCallback=true;for(const f of callbacks)f(this.count*33+1,{mediaTime:pts,presentedFrames:this.count,expectedDisplayTime:this.count*33,presentationTime:this.count*33-1,processingDuration:.003});this.inCallback=false}
    requestVideoFrameCallback(f){this.handles.set(++this.serial,f);return this.serial}
    cancelVideoFrameCallback(id){this.handles.delete(id)}
    play(){this.playRates.push(this.playbackRate);this.stopped=false;const tick=()=>{if(this.stopped)return;this.time=this.surface+1/30;this.present(this.time);setImmediate(tick)};setImmediate(tick);return Promise.resolve()}
    pause(){this.stopped=true}
    removeAttribute(){this.src=''}
  }
  global.document={body:{appendChild:()=>{}},createElement:tag=>{
    if(tag==='video'){const v=new Video();if(mode==='unsupported')v.requestVideoFrameCallback=undefined;return v}
    assert.equal(tag,'canvas');let value
    return{width:0,height:0,getContext:()=>({drawImage:v=>{assert.ok(v.inCallback,'must freeze within identified presentation');value=mode==='sourceTagged'?`${v.src}:${v.surface}`:v.surface}}),toDataURL:()=>`data:image/jpeg;base64,${Buffer.from(String(value)).toString('base64')}`}
  }}
  return{videos,restore:()=>{global.document=old}}
}
async function capture(t,id='test',signal=new AbortController().signal){return h.captureResearchFrame('blob:test',t,id,signal)}

test('requested time and actual PTS are distinct and verified against observed cadence',async()=>{const e=environment();try{const f=await capture(1.337);assert.equal(f.timing.requestedTime,1.337);assert.ok(Math.abs(f.timing.actualTime-1.333333333333)<1e-9);assert.equal(f.timing.seekedCurrentTime,1.337);assert.ok(f.timing.differenceSeconds<0);assert.ok(Object.isFrozen(f));assert.equal(f.timing.integrity,'VERIFIED')}finally{e.restore()}})
test('repeated timestamp captures have identical frozen pixels/fingerprint but separate record IDs',async()=>{const e=environment();try{const a=await capture(2.5,'one'),b=await capture(2.5,'two');assert.equal(a.imageDataUrl,b.imageDataUrl);assert.equal(a.imageFingerprint,b.imageFingerprint);assert.notEqual(a.frameId,b.frameId)}finally{e.restore()}})
test('forward, reverse and zero-first sequences never reuse a stale image',async()=>{const e=environment();try{for(const seq of [[2.5,5],[5,2.5],[0,2.5,5]]){const frames=[];for(const t of seq)frames.push(await capture(t));for(let i=0;i<seq.length;i++){assert.equal(frames[i].timing.actualTime,seq[i]);assert.equal(Buffer.from(frames[i].imageDataUrl.split(',')[1],'base64').toString(),String(seq[i]))}}}finally{e.restore()}})
test('stale surface after a successful seek is rejected rather than mislabeled',async()=>{const e=environment('stale');try{await assert.rejects(capture(2.5),/UNVERIFIED/)}finally{e.restore()}})
test('failed seek creates no frame and releases video resources',async()=>{const e=environment('errorSeek');try{await assert.rejects(capture(2.5),/failed/);assert.equal(e.videos[0].src,'');assert.equal(e.videos[0].handles.size,0)}finally{e.restore()}})
test('aborted seek creates no frame and cancels callbacks',async()=>{const e=environment('abortSeek'),a=new AbortController();try{const p=capture(2.5,'aborted',a.signal);setImmediate(()=>a.abort());await assert.rejects(p,/cancelled/);assert.equal(e.videos[0].handles.size,0)}finally{e.restore()}})
test('missing presented-frame API abstains explicitly',async()=>{const e=environment('unsupported');try{await assert.rejects(capture(0),/cannot report presented/)}finally{e.restore()}})
test('skipped/irregular presentations and snapped timestamps cannot silently pass',()=>{const p=(t,n,current=2.5)=>({mediaTime:t,presentedFrames:n,currentTime:current});assert.throws(()=>h.verifyTiming(2.5,p(0,1),p(2.5,2),p(2.53333,3)),/UNVERIFIED/);assert.throws(()=>h.verifyTiming(2.5,p(2.5,1),p(2.53333,3),p(2.56667,4)),/UNVERIFIED/);assert.throws(()=>h.verifyTiming(2.5,p(2.6,1),p(2.63333,2),p(2.66667,3)),/UNVERIFIED/)})
test('frame checksum rejects a stale detector image',async()=>{const e=environment();try{const f=await capture(5);h.assertFrozenInput(f,f.imageDataUrl);assert.throws(()=>h.assertFrozenInput(f,'data:old'),/does not match/)}finally{e.restore()}})
test('transactions serialize rapid requests and old completion cannot release newer lock',()=>{const g=new h.ResearchTransactions(),a=g.begin();assert.equal(g.begin(),null);g.cancel();const b=g.begin();assert.notEqual(a,b);assert.equal(g.current(a),false);g.finish(a);assert.equal(g.begin(),null);g.finish(b);assert.notEqual(g.begin(),null)})

function harness(){
  const oldMode=process.env.NODE_ENV;process.env.NODE_ENV='development'
  const slots=[];let index=0,pendingDetect,detected=[];let fail=false
  const react={useEffect:()=>{},useState:init=>{const i=index++;if(!(i in slots))slots[i]=init;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v]},useRef:init=>{const i=index++;if(!(i in slots))slots[i]={current:init};return slots[i]}}
  const jsx=(type,props)=>({type,props})
  const Component=load('src/app/pose-test/RawPoseResearch.tsx',{'./ResearchVideoSource':{__esModule:true,default:()=>null},'./RawPoseReview':{__esModule:true,default:()=>null},'@/lib/research-review':load('src/lib/research-review.ts'),'react':react,'react/jsx-runtime':{jsx,jsxs:jsx},'@/lib/pose-research':poseHelpers,'@/lib/pose-coherence':load('src/lib/pose-coherence.ts'),'@/lib/research-capture':{...h,downloadResearchJson:()=>{},captureResearchFrame:async(url,time,id)=>{if(fail)throw Error('seek failed');const imageDataUrl=`data:${url}:${time}`;return Object.freeze({frameId:id,timestampSeconds:time,imageDataUrl,width:100,height:100,imageFingerprint:h.imageFingerprint(imageDataUrl),timing:{requestedTime:time,actualTime:time-.001,integrity:'VERIFIED'}})}}}).default
  const pts=Array.from({length:33},(_,i)=>({x:.2,y:i*.01,visibility:.9}))
  const trace=image=>({sourceImage:image.src,records:[{poseIndex:1,raw:{source:'FULL_FRAME',passPose:1,input:image.src,width:100,height:100,fullWidth:100,sx:0,landmarks:pts},final:{poseIndex:1,landmarks:pts,bbox:{left:0,top:0,width:1,height:1}},retained:true,overlaps:[]}]})
  const props={video:'a',videoUrl:'blob:a',fingerprint:'a',frames:[],busy:false,detect:async image=>{detected.push(image.src);if(pendingDetect)await pendingDetect;return trace(image)}}
  const find=(tree,predicate)=>{if(!tree||typeof tree!=='object')return;if(predicate(tree))return tree;for(const c of [tree.props?.children].flat(Infinity)){const n=find(c,predicate);if(n)return n}}
  const render=()=>{index=0;return Component(props)}
  const label=name=>find(render(),n=>n.props?.['aria-label']===name)
  const button=name=>find(render(),n=>n.type==='button'&&n.props.children===name)
  const oldImage=global.Image;global.Image=class{set src(v){this._src=v;queueMicrotask(()=>this.onload())}get src(){return this._src}}
  return{props,slots,render,label,button,detected,find,fail:()=>fail=true,setPending:p=>pendingDetect=p,rows:()=>slots.find(s=>Array.isArray(s)&&s[0]?.stage)||[],restore:()=>{global.Image=oldImage;if(oldMode===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=oldMode}}
}
test('component links displayed, detected and recorded frame and preserves labels on repeat',async()=>{const x=harness();try{x.label('Research timestamp').props.onChange({target:{value:'2.5'}});await x.button('Inspect research frame').props.onClick();const first=x.rows()[0];x.find(x.render(),n=>Array.isArray(n.props?.records)).props.onAction(first.id,{type:'commit',label:'COHERENT',note:'',at:'test'});await x.button('Inspect research frame').props.onClick();const rows=x.rows();assert.equal(rows.length,4);assert.equal(rows[0].label,'COHERENT');assert.equal(rows[2].label,'UNLABELED');assert.notEqual(rows[0].id,rows[2].id);assert.equal(rows[0].frameFingerprint,rows[2].frameFingerprint);assert.equal(first.requestedTime,2.5);assert.equal(first.actualTime,2.499);const overlay=x.find(x.render(),n=>n.props?.name==='Research pose overlay');assert.equal(overlay.props.image,x.detected[1]);assert.equal(h.imageFingerprint(overlay.props.image),rows[2].frameFingerprint);assert.equal(rows[2].detectorInputFingerprint,rows[2].sourceImageFingerprint)}finally{x.restore()}})
test('component ignores stale detection across A to B to A video changes',async()=>{const x=harness();try{let resolve;const blocked=new Promise(r=>resolve=r);x.setPending(blocked);const old=x.button('Inspect research frame').props.onClick();await new Promise(setImmediate);assert.equal(x.detected.length,1);await x.button('Inspect research frame').props.onClick();assert.equal(x.detected.length,1);x.props.videoUrl='blob:b';x.props.fingerprint='b';x.render();x.props.videoUrl='blob:a';x.props.fingerprint='a';x.render();x.setPending(null);x.label('Research timestamp').props.onChange({target:{value:'5'}});await x.button('Inspect research frame').props.onClick();assert.equal(x.detected.length,1);resolve();await old;await x.button('Inspect research frame').props.onClick();assert.equal(x.rows().length,2);assert.equal(x.rows()[0].requestedTime,5)}finally{x.restore()}})
test('component failed capture creates no valid rows or detection',async()=>{const x=harness();try{x.fail();await x.button('Inspect research frame').props.onClick();assert.equal(x.rows().length,0);assert.equal(x.detected.length,0)}finally{x.restore()}})

test('local selector cancels old detection and first new capture records the selected source',async()=>{
 const mode=process.env.NODE_ENV;process.env.NODE_ENV='development';const x=harness()
 try{
  const switchSource=(video,ready)=>x.find(x.render(),n=>typeof n.props?.onChange==='function'&&typeof n.type==='function').props.onChange(video,ready)
  const a={id:'local-a',filename:'a.mp4',url:'/pose-test/research-videos/a'},b={id:'local-b',filename:'b.mp4',url:'/pose-test/research-videos/b'}
  switchSource(a,true);x.label('Research timestamp').props.onChange({target:{value:'2.5'}})
  let release;x.setPending(new Promise(r=>release=r));const old=x.button('Inspect research frame').props.onClick();await new Promise(setImmediate)
  switchSource(b,false);assert.equal(x.button('Inspect research frame').props.disabled,true);assert.equal(x.label('Research timestamp').props.value,'0')
  switchSource(b,true);x.setPending(null);release();await old;assert.equal(x.rows().length,0)
  x.label('Research timestamp').props.onChange({target:{value:'5.767'}});await x.button('Inspect research frame').props.onClick()
  assert.equal(x.rows()[0].video,'b.mp4');assert.equal(x.rows()[0].fingerprint,'local-b');assert.equal(x.rows()[0].requestedTime,5.767);assert.ok(x.detected.at(-1).includes(b.url))
  switchSource(a,true);await x.button('Inspect research frame').props.onClick();assert.equal(x.rows()[2].fingerprint,'local-a');assert.notEqual(x.rows()[0].frameFingerprint,x.rows()[2].frameFingerprint)
  switchSource(null,false);await x.button('Inspect research frame').props.onClick();assert.equal(x.rows()[4].fingerprint,'a');assert.equal(x.props.videoUrl,'blob:a')
 }finally{x.restore();if(mode===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=mode}
})
test('JSON export matches current session and excludes image blobs, traces and raw arrays',async()=>{const x=harness();try{x.label('Research timestamp').props.onChange({target:{value:'1.337'}});await x.button('Inspect research frame').props.onClick();const row=x.rows()[0];const text=h.researchExport([{...row,imageDataUrl:'data:secret',landmarks:[1,2],trace:{raw:[3]},rawLandmarks:[4]}]);const exported=JSON.parse(text);assert.equal(exported.authority,'NONE');assert.equal(exported.rows[0].requestedTime,1.337);assert.equal(exported.rows[0].actualTime,1.336);assert.equal(exported.rows[0].frameFingerprint,row.frameFingerprint);assert.doesNotMatch(text,/data:secret|imageDataUrl|landmarks|rawLandmarks|"trace"/);x.button('Export research JSON (no images)').props.onClick();assert.equal(JSON.parse(x.label('Research JSON export').props.value).rows.length,x.rows().length)}finally{x.restore()}})
test('download anchors are attached and URL remains valid through click',()=>{const oldDoc=global.document,oldTimer=global.setTimeout,oldCreate=URL.createObjectURL,oldRevoke=URL.revokeObjectURL;let attached=false,clicked=false,removed=false,revoked=false,cleanup;try{URL.createObjectURL=()=> 'blob:export';URL.revokeObjectURL=()=>revoked=true;global.setTimeout=(f,ms)=>{assert.ok(ms>0);cleanup=f};global.document={body:{appendChild:()=>attached=true},createElement:()=>({click:()=>{assert.ok(attached);assert.equal(revoked,false);clicked=true},remove:()=>removed=true})};h.downloadResearchJson('{"authority":"NONE","rows":[]}');assert.ok(clicked&&removed);assert.equal(revoked,false);cleanup();assert.ok(revoked)}finally{global.document=oldDoc;global.setTimeout=oldTimer;URL.createObjectURL=oldCreate;URL.revokeObjectURL=oldRevoke}})
test('capture helper has no product authority or product imports',()=>{const src=fs.readFileSync(path.resolve(__dirname,'../src/lib/research-capture.ts'),'utf8');assert.doesNotMatch(src,/from ['"]|fetch\(|localStorage|sessionStorage|TARGET_A|coachingEligible/);assert.equal(JSON.parse(h.researchExport([])).authority,'NONE')})

test('presentation preceding seeked is frozen then waits for seek completion',async()=>{const e=environment('presentationFirst');try{const f=await capture(5);assert.equal(f.timing.actualTime,5);assert.equal(f.timing.seekedCurrentTime,5);assert.ok(f.timing.seekedElapsedMs>=f.timing.presentation.elapsedMs)}finally{e.restore()}})

// Accelerate watchdogs only in tests; production keeps its original 15-second bound.
async function quickWatchdogs(work){const original=global.setTimeout;global.setTimeout=(f,ms,...args)=>original(f,Math.min(ms,25),...args);try{return await work()}finally{global.setTimeout=original}}
test('initial callback before loadeddata drains without waiting for another paused frame',async()=>{const e=environment('initialBeforeData');try{const f=await capture(2.5);assert.equal(f.timing.attempts.length,1);assert.equal(f.timing.actualTime,2.5);const events=f.timing.attempts[0].events;assert.equal(events.find(e=>e.event==='presentationReceived').readyState,1);assert.ok(events.some(e=>e.event==='seekStart'&&e.readyState===4))}finally{e.restore()}})
test('missing first sought callback retries same timestamp and preserves both attempts',async()=>{const e=environment('missingFirst');try{await quickWatchdogs(async()=>{const f=await capture(2.5);const a=f.timing.attempts;assert.equal(a.length,2);assert.equal(a[0].reason,'PRESENTATION_TIMEOUT');assert.equal(a[1].outcome,'VERIFIED');assert.deepEqual(a.map(a=>a.requestedTime),[2.5,2.5]);assert.notEqual(a[0].attemptId,a[1].attemptId);assert.notEqual(a[0].elementId,a[1].elementId);assert.equal(f.timing.actualTime,2.5);assert.ok(a[0].events.some(e=>e.event==='seeked'));assert.ok(a[0].events.some(e=>e.event==='timeout:sought presentation'))})}finally{e.restore()}})
test('all presentation retries fail with exactly three attempts and no frame',async()=>{const e=environment('missingAll');try{await quickWatchdogs(async()=>{await assert.rejects(capture(2.5),error=>{assert.equal(error.reason,'PRESENTATION_TIMEOUT');assert.equal(error.attempts.length,3);assert.ok(error.attempts.every(a=>a.outcome==='REJECTED'));return true});assert.equal(e.videos.length,3);assert.ok(e.videos.every(v=>v.handles.size===0&&v.src===''))})}finally{e.restore()}})
test('seek, presentation, and readiness timeouts have distinct diagnostic reasons',async()=>{for(const [mode,reason] of [['seekTimeout','SEEK_TIMEOUT'],['missingAll','PRESENTATION_TIMEOUT'],['loadTimeout','VIDEO_NOT_READY']]){const e=environment(mode);try{await quickWatchdogs(()=>assert.rejects(capture(2.5),error=>error.reason===reason&&error.attempts.length===3))}finally{e.restore()}}})
test('late callback from an aborted sub-attempt cannot freeze or affect a later transaction',async()=>{const e=environment('abortSeek'),abort=new AbortController();try{const old=capture(2.5,'old',abort.signal);await new Promise(setImmediate);const callbacks=[...e.videos[0].handles.values()];abort.abort();await assert.rejects(old,/cancelled/);for(const f of callbacks)f(0,{mediaTime:2.5,presentedFrames:2,expectedDisplayTime:1});assert.equal(e.videos[0].handles.size,0);assert.equal(e.videos[0].src,'')}finally{e.restore()}})
test('source change cancellation has explicit provenance and cannot retry',async()=>{const e=environment('abortSeek'),abort=new AbortController();try{const pending=capture(2.5,'source-old',abort.signal);await new Promise(setImmediate);abort.abort('SOURCE_CHANGE');await assert.rejects(pending,error=>error.reason==='SOURCE_CHANGE'&&error.attempts.length===1&&error.attempts[0].state==='CANCELLED')}finally{e.restore()}})
test('first frame on a new source uses its own decoder and fingerprint',async()=>{const e=environment('sourceTagged');try{const a=await h.captureResearchFrame('blob:a',2.5,'a',new AbortController().signal,{sourceId:'A'});const b=await h.captureResearchFrame('blob:b',2.5,'b',new AbortController().signal,{sourceId:'B'});assert.notEqual(a.imageFingerprint,b.imageFingerprint);assert.equal(b.timing.attempts[0].sourceId,'B');assert.equal(e.videos[0].src,'');assert.equal(e.videos[1].src,'')}finally{e.restore()}})
test('batch awaits detection and record completion before starting next timestamp',async()=>{const e=environment();try{const order=[],results=[];let active=0;await h.runResearchBatch([5,2.5,2.5],new AbortController().signal,async(t,i)=>{assert.equal(active++,0);order.push(`start:${i}`);const f=await capture(t,`batch-${i}`);await new Promise(setImmediate);order.push(`detected:${i}`);active--;return f},r=>{order.push(`record:${results.length}`);results.push(r)});assert.deepEqual(order,['start:0','detected:0','record:0','start:1','detected:1','record:1','start:2','detected:2','record:2']);assert.equal(results[1].frameFingerprint,results[2].frameFingerprint);assert.ok(results.every(r=>r.status==='VERIFIED'));assert.deepEqual(results.map(r=>r.actualTime),[5,2.5,2.5])}finally{e.restore()}})
test('failed batch item records its reason and leaves next timestamp independent',async()=>{const e=environment(),results=[];try{await h.runResearchBatch([30,2.5],new AbortController().signal,t=>capture(t),r=>results.push(r));assert.deepEqual(results.map(r=>r.status),['REJECTED','VERIFIED']);assert.match(results[0].reason,/before video end/);assert.equal(results[1].actualTime,2.5)}finally{e.restore()}})
test('cancellation during detection publishes no verified batch item and stops sequence',async()=>{const e=environment(),abort=new AbortController(),results=[];let calls=0;try{await h.runResearchBatch([2.5,5],abort.signal,async t=>{calls++;const f=await capture(t);abort.abort();return f},r=>results.push(r));assert.equal(calls,1);assert.equal(results.length,1);assert.equal(results[0].status,'REJECTED');assert.equal(results[0].state,'CANCELLED')}finally{e.restore()}})
test('actual timestamp outside coverage stays rejected through every retry',async()=>{const e=environment('stale');try{await assert.rejects(capture(2.5),error=>{assert.equal(error.reason,'PRESENTATION_SKIPPED');assert.equal(error.attempts.length,3);assert.ok(error.attempts.every(a=>a.outcome==='REJECTED'));return true})}finally{e.restore()}})
test('batch component serializes detection, keeps labels manual, and rejects concurrent clicks',async()=>{const x=harness();try{let release;const pending=new Promise(r=>release=r);x.setPending(pending);x.label('Research batch timestamps').props.onChange({target:{value:'5,2.5,2.5'}});const batch=x.button('Run research batch').props.onClick();await new Promise(setImmediate);assert.equal(x.detected.length,1);await x.button('Run research batch').props.onClick();assert.equal(x.detected.length,1);x.setPending(null);release();await batch;assert.equal(x.detected.length,3);assert.equal(x.rows().length,6);assert.ok(x.rows().every(r=>r.label==='UNLABELED'));const d=JSON.parse(x.label('Research batch results').props.value);assert.deepEqual(d.results.map(r=>r.requestedTime),[5,2.5,2.5])}finally{x.restore()}})
test('batch cancellation while detection is pending creates no pose row',async()=>{const x=harness();try{let release;x.setPending(new Promise(r=>release=r));x.label('Research batch timestamps').props.onChange({target:{value:'2.5,5'}});const batch=x.button('Run research batch').props.onClick();await new Promise(setImmediate);x.button('Cancel research capture').props.onClick();release();await batch;assert.equal(x.detected.length,1);assert.equal(x.rows().length,0)}finally{x.restore()}})
test('verification function remains exactly the checkpoint standard',()=>{const {execFileSync}=require('child_process');const base=execFileSync('git',['show','c033a7fc8fe5911c91b5792e5bac6d33ce488e0f:src/lib/research-capture.ts'],{encoding:'utf8'});const current=fs.readFileSync(path.resolve(__dirname,'../src/lib/research-capture.ts'),'utf8');const fn=s=>s.slice(s.indexOf('export function verifyTiming'),s.indexOf('export class ResearchTransactions')).replace(/\r\n/g,'\n');assert.equal(fn(current),fn(base))})
test('Shadow v0 bytes remain frozen throughout batch capture changes',()=>{const crypto=require('crypto');const model=fs.readFileSync(path.resolve(__dirname,'../src/lib/pose-coherence.ts'));assert.equal(crypto.createHash('sha256').update(model).digest('hex'),'c0d04a35018f96211bb9cbe3d91efd27ff56cee16e5e04a3016fcaa5a9b7b9c7')})

test('warm-up drains sought callback before readiness but only fresh prepared callback can freeze',async()=>{const e=environment('warmReadinessRace');try{const f=await capture(2.5);assert.equal(f.timing.attempts.length,1);assert.equal(f.timing.actualTime,2.5);assert.ok(f.timing.presentation.presentedFrames>=4);const events=f.timing.attempts[0].events;assert.ok(events.some(e=>e.event==='presentationReceived'&&e.mediaTime===2.5&&e.readyState===1));assert.ok(events.some(e=>e.event==='warmComplete'));assert.ok(events.filter(e=>e.stage==='FREEZING_FRAME').every(e=>e.readyState>=2))}finally{e.restore()}})

test('research preparation and witness playback stay at native speed',async()=>{const e=environment();try{await capture(2.5);assert.equal(e.videos[0].defaultPlaybackRate,1);assert.deepEqual(e.videos[0].playRates,[1,1])}finally{e.restore()}})
test('complete callback history retains sequence, compositor timing, seek and source provenance',async()=>{const e=environment();try{const f=await capture(2.5,'metadata');const a=f.timing.attempts[0],callbacks=a.events.filter(e=>e.event==='presentationReceived');assert.equal(callbacks.length,6);assert.deepEqual(callbacks.map(e=>e.callbackSequence),[1,2,3,4,5,6]);for(const event of callbacks){assert.ok(Number.isFinite(event.callbackNow));assert.ok(Number.isFinite(event.expectedDisplayTime));assert.ok(Number.isFinite(event.presentationTime));assert.ok(Number.isFinite(event.wallClockMs));assert.equal(event.processingDuration,.003);assert.ok(event.witness)}assert.equal(callbacks.at(-1).seekedTime,2.5);assert.equal(a.transactionId,'metadata');assert.ok(a.sourceId);assert.ok(a.attemptId)}finally{e.restore()}})
